### ISSUE TITLE
GetCloseTag() runtime error - vim 7.4

### ISSUE THREAD

**Issue by HelloMihai** [alvan/vim-closetag#4]
Hello, I have the following `.vimrc` setup:
![2016-03-21_23-45-16](https://cloud.githubusercontent.com/assets/8506019/13944040/f9ffb740-efbe-11e5-9fdc-dad70f268503.png)

typing `<sometag>` , exiting to the command and `Ctrl+_` shows the following error:
![2016-03-21_23-48-02](https://cloud.githubusercontent.com/assets/8506019/13944090/5d64974c-efbf-11e5-85b7-78f56859d17f.png)

after the error the tag closes correcty:
![2016-03-21_23-48-46](https://cloud.githubusercontent.com/assets/8506019/13944102/7682ace6-efbf-11e5-9e3e-4600771a968e.png)

this is my `vim --version`
![2016-03-21_23-49-51](https://cloud.githubusercontent.com/assets/8506019/13944116/9d010994-efbf-11e5-99e1-33a2daf4dbd9.png)

Thank you for your time.  I love this addon and hoping to try and get it to work.

**Comment by alvan** [comment]
Hi @HelloMihai 
This error NOT caused by https://github.com/alvan/vim-closetag/,
you should check your $VIM/_/autoload/htmlcomplete.vim and $VIM/_/autoload/xmlcomplete.vim, there should be some errors.
And if you are using vim-closetag, you don't have to press `<Ctrl+_>` to complete tags,
see https://github.com/alvan/vim-closetag/blob/master/README.md for more details.
